// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.jsx";
import * as $1 from "./routes/_middleware.js";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/index.jsx";
import * as $4 from "./routes/login.jsx";
import * as $5 from "./routes/logout.jsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Login.jsx";

const manifest = {
  routes: {
    "./routes/_404.jsx": $0,
    "./routes/_middleware.js": $1,
    "./routes/api/joke.ts": $2,
    "./routes/index.jsx": $3,
    "./routes/login.jsx": $4,
    "./routes/logout.jsx": $5,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Login.jsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
